/**
 * Photo data + helpers. images.json is generated by scripts/optimize-images.mjs.
 *
 * Taken from the current studiokunalphotography.com website. Do not add awards,
 * statistics, venues, prices or reviews that are not published by the studio.
 */
import images from "./images.json";

export type Photo = { src: string; width: number; height: number; blur: string };

export const home = images.home as Photo[];
export const img = images as unknown as Record<string, Photo[]> & { films: Record<string, Photo> };

/** 1-indexed helper for the homepage image set. */
export const homePhoto = (n: number) => home[n - 1];
